#requires -Version 7.0
# Offline unit test for _webui-config.ps1 (no cloud). Run: pwsh -File .github/skills/agent365-web-ui/scripts/test-webui-config.ps1
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '_webui-config.ps1')

$fail = 0
function Assert($cond, $msg) { if ($cond) { Write-Host "  PASS $msg" -ForegroundColor Green } else { Write-Host "  FAIL $msg" -ForegroundColor Red; $script:fail++ } }

# --- Sample deployed config.js (pure JSON, two labs already present) ---
$sample = @'
// Generated by scaffold-from-plan.ps1
window.APP_CONFIG = {
  "msal": { "clientId": "spa-app-id", "authority": "https://login.microsoftonline.com/tenant" },
  "agents": [
    { "id": "obo-a09091", "kind": "aca", "name": "A (ACA, OBO)", "apiBase": "https://a.example", "scope": "ea9ffc3e-8a23-4a7d-836d-234d7c7565c1/McpServers.Mail.All", "enabled": true, "labPrefix": "a09091" },
    { "id": "s2s-a09101", "kind": "aca", "name": "B (ACA, S2S)", "apiBase": "https://b.example", "scope": "api://x/access_agent_as_user", "enabled": true, "labPrefix": "a09101" }
  ]
};
'@

Write-Host "Read/Write round-trip" -ForegroundColor Cyan
$cfg = Read-AppConfig -Text $sample
Assert ($cfg.msal.clientId -eq 'spa-app-id') "msal preserved"
Assert (@($cfg.agents).Count -eq 2) "two tabs parsed"
$out = Write-AppConfig -Config $cfg
Assert ($out -match 'window\.APP_CONFIG = ') "serializes wrapper"
$cfg2 = Read-AppConfig -Text $out
Assert (@($cfg2.agents).Count -eq 2) "re-parse after write"

Write-Host "New-TabEntry shapes" -ForegroundColor Cyan
$e = New-TabEntry -AgentType 'ACA-OBO' -Name 'My Mail (ACA, OBO)' -LabPrefix 'zz1' -ApiBase 'https://obo.fqdn' -AnonAudience 'aud-anon' -AuthAudience 'aud-auth'
Assert ($e['id'] -eq 'obo-zz1') "ACA-OBO id derived"
Assert ($e['kind'] -eq 'aca') "ACA-OBO kind"
Assert ($e['customScopes']['aud-anon'] -eq 'aud-anon/Tools.ListInvoke.All') "ACA-OBO customScopes"
Assert ($e['labPrefix'] -eq 'zz1' -and $e['enabled'] -eq $true) "ACA-OBO owner+enabled"
$f = New-TabEntry -AgentType 'FD-OBO' -Name 'FD' -LabPrefix 'zz1' -Endpoint 'https://x/openai/v1/responses' -AgentName 'zz1-MAF-FD-OBO' -AnonAudience 'aud-anon'
Assert ($f['kind'] -eq 'foundry-prompt' -and $f['customInputs']['anon_token'] -eq 'aud-anon/Tools.ListInvoke.All') "FD-OBO customInputs"
$g = New-TabEntry -AgentType 'FH-OBO' -Name 'FH' -LabPrefix 'zz1' -Endpoint 'https://x/invocations'
Assert ($g['sessionPrefix'] -eq 'obo-fh') "FH-OBO sessionPrefix"

Write-Host "Add-OrReplaceTab (append + idempotent replace)" -ForegroundColor Cyan
$cfg = Read-AppConfig -Text $sample
$cfg = Add-OrReplaceTab -Config $cfg -Entry $e
Assert (@($cfg.agents).Count -eq 3) "append new tab -> 3"
Assert (@($cfg.agents | Where-Object { $_.id -eq 'obo-a09091' }).Count -eq 1) "other lab tab preserved"
# Re-add same id -> still 3 (replace, not duplicate)
$e2 = New-TabEntry -AgentType 'ACA-OBO' -Name 'My Mail v2' -LabPrefix 'zz1' -ApiBase 'https://obo.fqdn2'
$cfg = Add-OrReplaceTab -Config $cfg -Entry $e2
Assert (@($cfg.agents).Count -eq 3) "replace same id -> still 3"
Assert ((@($cfg.agents | Where-Object { $_.id -eq 'obo-zz1' })[0].apiBase) -eq 'https://obo.fqdn2') "replaced content"

Write-Host "Remove-TabsByLab (surgical, preserves others)" -ForegroundColor Cyan
$removed = Remove-TabsByLab -Config $cfg -LabPrefix 'zz1'
Assert ($removed -eq 1) "removed 1 zz1 tab"
Assert (@($cfg.agents).Count -eq 2) "back to 2"
Assert (@($cfg.agents | Where-Object { $_.labPrefix -eq 'a09091' }).Count -eq 1 -and @($cfg.agents | Where-Object { $_.labPrefix -eq 'a09101' }).Count -eq 1) "both original labs intact"

Write-Host "Remove-TabsByLab fallback by id suffix (no labPrefix field)" -ForegroundColor Cyan
$legacy = @'
window.APP_CONFIG = { "msal": { "clientId": "c", "authority": "a" }, "agents": [ { "id": "obo-old", "kind": "aca", "name": "old" }, { "id": "s2s-keep", "kind": "aca", "name": "keep" } ] };
'@
$lc = Read-AppConfig -Text $legacy
$r = Remove-TabsByLab -Config $lc -LabPrefix 'old'
Assert ($r -eq 1 -and @($lc.agents).Count -eq 1 -and $lc.agents[0].id -eq 's2s-keep') "id-suffix fallback removed only obo-old"

Write-Host "Remove-TabById" -ForegroundColor Cyan
$cfg = Read-AppConfig -Text $sample
$r = Remove-TabById -Config $cfg -TabId 'obo-a09091'
Assert ($r -eq 1 -and @($cfg.agents).Count -eq 1 -and $cfg.agents[0].id -eq 's2s-a09101') "removed exactly one by id"

Write-Host "Malformed config is rejected with a clear error" -ForegroundColor Cyan
$threw = $false
try { Read-AppConfig -Text 'window.APP_CONFIG = { "agents": [ , not-json }' } catch { $threw = $true }
Assert $threw "malformed JSON rejected with a clear error"

Write-Host ""
if ($fail -eq 0) { Write-Host "ALL TESTS PASSED" -ForegroundColor Green; exit 0 } else { Write-Host "$fail TEST(S) FAILED" -ForegroundColor Red; exit 1 }
