#requires -Version 7.0
<#
.SYNOPSIS
  Writes the operator hand-outs of a demo lab to generated/<prefix>/demo/cards: the guided cards of the manual (portal)
  configuration and the test hand-out, in English with the localized values of the lab (names, instructions, prompts).
.DESCRIPTION
  Cards: one per template in ../references/cards/*.md (placeholders expanded; the Copilot Studio and Agent Builder
  templates also get one generated section per agent of the pack), then 90-test-handout.md with every test of pack.json
  (persona + UPN, surface, prompt(s), expected result) and 00-index.md.
  Template placeholders: {{locale.path}}, {upn:<persona>|admin}, {name:<persona>|admin}, {agent:<key>}, {group:<key>},
  {folder:<key>}, {cfg:<path>}, {state:<path>}, {pack:<path>}, {slot:<id>}; the lines <!-- AGENTS:copilotStudio --> and
  <!-- AGENTS:agentBuilder --> receive the generated agent sections.
  Operator slots are never printed: a prompt or document that uses one shows 'fill slot-N' (see OPERATOR-SLOTS.md).
.EXAMPLE
  pwsh -File .\New-DemoCards.ps1 -Prefix cts2
#>
[CmdletBinding(PositionalBinding = $false)]
param([Parameter(Mandatory)][string]$Prefix)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '_demo-common.ps1')
$cfg = Read-DemoConfig $Prefix
$pack = Get-DemoPack $cfg.pack
$LOC = Get-DemoLocale -Locale $cfg.locale -Pack $cfg.pack
$state = Read-DemoLabState $Prefix
$tplDir = Join-Path (Split-Path -Parent $PSScriptRoot) 'references\cards'
$outDir = Join-Path (Get-DemoLabDir $Prefix) 'cards'

function Get-Upn([string]$Key) { Get-DemoUpn $LOC $cfg $Key }
function Get-Who([string]$Key) { if ($Key -eq 'admin') { return "the tenant administrator ($($cfg.adminUpn))" }; "$(Get-DemoPersonaDisplayName $LOC $Key) ($(Get-Upn $Key))" }
function Get-SlotText([string]$Id) { Get-DemoSlotText $Id ([string]$cfg.pack) }
function Format-Code([string]$S) { '`' + $S + '`' }
function Expand-CardText([string]$Text) { Expand-DemoText $Text $LOC $cfg $state $pack }
function Format-Block([string]$Text) { if (-not $Text) { return '_(empty on purpose)_' }; return ('```text' + "`n" + $Text + "`n" + '```') }
function Get-DemoList($Codes) { $c = @($Codes | Where-Object { $_ }); if ($c.Count) { "Used in: $($c -join ', ')." } else { '' } }
function Get-FolderText([string]$Key) {
    $lib = if ($state.knowledge -and $state.knowledge.libraryUrl) { "of the library $($state.knowledge.libraryUrl)" } else { 'of the demo SharePoint library (publish it first: Publish-DemoKnowledge.ps1)' }
    "SharePoint folder **$($LOC.knowledge.folders[$Key])** $lib"
}

# One section per Copilot Studio agent of the pack.
function Get-CopilotStudioSections {
    $n = 0
    foreach ($a in @($pack.agents | Where-Object { $_.platform -eq 'copilotStudio' } | Sort-Object { [int]$_.buildOrder })) {
        $n++; $la = $LOC.agents[$a.key]
        $cfgFrom = if ($a.sameConfigAs) { $LOC.agents[$a.sameConfigAs] } else { $la }
        $envName = if ($a.environment -eq 'default') { "the tenant DEFAULT environment ($($cfg.copilotStudio.defaultEnvironmentId))" } else { "the pay-as-you-go environment ($($cfg.copilotStudio.paygEnvironmentId))" }
        $owner = if ($a.registryOwner -and $a.registryOwner -ne 'none') { Get-Who $a.registryOwner } else { 'the tenant administrator' }
        $know = if ($a.knowledgeFolder) { Get-FolderText $a.knowledgeFolder }
                elseif ($a.knowledgeUpload) { 'upload ' + (@($a.knowledgeUpload | ForEach-Object { '**' + $LOC.knowledge.documents[$_].file + '**' }) -join ', ') + ' (generated by New-DemoKnowledge.ps1)' }
                elseif ($a.sameConfigAs) { 'same as ' + $LOC.agents[$a.sameConfigAs].displayName } else { 'none' }
        $isNh = $a.variant -eq 'MCS-NH'
        $outside = if ($a.outsideLabPlan) { ' (created OUTSIDE the Lab Builder plan: command in outside-plan.json)' } else { '' }
        $desc = if ($isNh) { 'none on the Build page (new harness); use it in the channel details only if offered: ' + (Format-Code $cfgFrom.shortDescription) } else { Format-Code $cfgFrom.description }
        $knowNote = if ($isNh) { '; REMOVE the default "Search all websites" knowledge of the base solution' } else { '' }
        $tools = if (@($a.tools | Where-Object { $_ }).Count) { (@($a.tools) -join ', ') + $(if ($a.authentication -eq 'microsoft') { ' (authentication: Microsoft)' } else { '' }) } else { 'none' }
        if ($isNh) { $tools += ' (new-harness agents accept no BYO MCP server)' }
        $memory = if ($a.memory -eq $false) { '; Memory off' } else { '' }
        $channelNames = @{ microsoft365Copilot = 'Microsoft 365 Copilot'; teams = 'Teams'; demoWebsite = 'Demo website' }
        $channels = @($a.channels | ForEach-Object { if ($channelNames.ContainsKey([string]$_)) { $channelNames[[string]$_] } else { [string]$_ } }) -join ', '
        $auth = if ($a.authentication -eq 'none') { 'NO authentication (a deliberate weakness of the demo)' } else { 'default (Microsoft)' }
        $lines = @("### C$n. $($la.displayName) ($($a.variant))", '',
            "- **Who**: $owner creates, configures and publishes it in $envName$outside."
            "- **Name**: $(Format-Code $la.displayName)"
            "- **Description**: $desc"
            "- **Knowledge**: $know$knowNote."
            "- **Tools**: $tools."
            "- **Channels**: $channels$memory; developer name $(Format-Code $LOC.org.publisher)."
            "- **Authentication**: $auth."
            '- **Instructions**:', '', (Format-Block ([string]$cfgFrom.instructions)), '')
        $b = $a.baseline
        if ($b) {
            $state0 = @()
            if ($b.installedFor) { $state0 += "published to the organization catalog, approved and **installed for** $(if ($b.installedFor -like 'group:*') { "the group $($LOC.groups[$b.installedFor.Substring(6)].displayName)" } else { Get-Who ($b.installedFor -replace '^persona:', '') })" }
            if ($b.pendingRequest) { $state0 += 'submitted to the organization catalog and left **PENDING** (approved live)' }
            if ($b.blocked) { $state0 += '**blocked** in the admin center (published entry)' }
            if ($b.usage) { $state0 += 'used at least once in a published channel (Preview creates no usage)' }
            if ($state0.Count) { $lines += "- **Starting state**: $($state0 -join '; ')." }
        }
        if (@($a.weaknesses | Where-Object { $_ }).Count) { $lines += "- **Deliberate weaknesses** (do not fix them): $(@($a.weaknesses) -join ', ')." }
        $lines += (Get-DemoList $a.demos), ''
        $lines -join "`n"
    }
}

# One section per Agent Builder agent of the pack (created by a persona in Microsoft 365 Copilot).
function Get-AgentBuilderSections {
    $n = 0
    foreach ($a in @($pack.agents | Where-Object { $_.platform -eq 'agentBuilder' } | Sort-Object { [int]$_.buildOrder })) {
        $n++; $la = $LOC.agents[$a.key]
        $know = if ($a.knowledgeFolder) { Get-FolderText $a.knowledgeFolder }
                elseif ($a.knowledgePersonal) { "the personal file **$($LOC.knowledge.personal[$a.knowledgePersonal].file)** in the creator's OneDrive (generated by New-DemoKnowledge.ps1)" } else { 'none' }
        $lines = @("### B$n. $($la.displayName)", '',
            "- **Who**: $(Get-Who $a.creator) signs in to Microsoft 365 Copilot > Create agent (Agent Builder).$(if ($a.leaver) { ' This person is a LEAVER: create the agent BEFORE the account is deleted (see the reset lead times).' })"
            "- **Name**: $(Format-Code $la.displayName)"
            "- **Description**: $(Format-Code $la.description)"
            "- **Knowledge**: $know."
            "- **Share with**: $(if ($a.shareWith) { "the group $($LOC.groups[$a.shareWith].displayName)" } else { 'nobody' })$(if ($a.baseline.pendingRequest) { '; then submit it to the organization catalog and leave the request PENDING' })."
            '- **Instructions**:', '', (Format-Block ([string]$la.instructions)), '')
        if (@($a.shareLinkOpenedBy | Where-Object { $_ }).Count) {
            $lines += "- **Share link**: right after sharing, $(@($a.shareLinkOpenedBy | ForEach-Object { Get-Who $_ }) -join ', ') each open it once (the pre-flight prints it)."
        }
        if ($a.submitToCatalog) {
            $site = if ($state.knowledge -and $state.knowledge.libraryUrl) { ([string]$state.knowledge.libraryUrl) -replace '/[^/]+$', '' } else { 'the demo SharePoint site URL' }
            $dev = if ($a.submitToCatalog.developer -eq 'creator') { Get-DemoPersonaDisplayName $LOC $a.creator } else { [string]$LOC.org.publisher }
            $lines += "- **Catalog submission**: display name $(Format-Code $la.displayName), short description $(Format-Code $la.description), developer $(Format-Code $dev) (a personal initiative), website/privacy/terms $site; Org-wide sharing for chat access **off**."
        }
        if ($la.rejectionReason) { $lines += "- **Rejection reason** (typed live by the admin): $(Format-Code $la.rejectionReason)" }
        $lines += (Get-DemoList $a.demos), ''
        $lines -join "`n"
    }
}
# --- Test hand-out ------------------------------------------------------------------------------------------------
$surfaces = @{ webUi = 'web UI'; teams = 'Teams'; outlook = 'Outlook'; m365Copilot = 'Microsoft 365 Copilot'; copilotStudio = 'Copilot Studio (test pane)'; foundry = 'Foundry portal (playground)' }
function Expand-Prompt([string]$P) {
    $out = $P
    $inst = @($pack.agents | Where-Object { $_.instance }) | Select-Object -First 1
    if ($inst) { $out = $out.Replace('{upn:instance}', "$($LOC.agents[$inst.key].instance.alias)@$($cfg.domain)") }
    return [regex]::Replace($out, '\{upn:([A-Za-z0-9]+)\}', [System.Text.RegularExpressions.MatchEvaluator]{ param($m) Get-Upn $m.Groups[1].Value })
}
function Format-Prompt([string]$P) { $e = Expand-Prompt $P; if ($e.Contains("`n")) { return ("`n" + (Format-Block $e)) }; return (Format-Code $e) }
function Get-TestSection($t) {
    $it = if ($LOC.tests.items -and $LOC.tests.items.Contains($t.id)) { $LOC.tests.items[$t.id] } else { $null }
    $agentName = if ($t.agent) { [string]$LOC.agents[$t.agent].displayName } else { '' }
    $surface = if ($surfaces.ContainsKey([string]$t.surface)) { $surfaces[[string]$t.surface] } else { [string]$t.surface }
    $who = @(@($t.persona) + @($t.personas) | Where-Object { $_ } | ForEach-Object { if ($_ -eq 'anyone') { 'any licensed demo user' } else { Get-Who $_ } })
    $lines = @("### $($t.id) · $agentName · $surface", '', "- **Who**: $($who -join '; ')")
    $when = @()
    if ($t.phase) { $when += "phase $($t.phase)" }
    if ($t.after) { $when += "after $($t.after)" }
    if ($t.window) { $when += "window $($t.window)" }
    if ($t.conversationsPerPersona) { $when += "at least $($t.conversationsPerPersona) conversations per person" }
    if ($t.repeatTimes) { $when += "send it $($t.repeatTimes) times" }
    if ($t.needsConnection) {
        $srv = if ($state.mcp.servers -and $state.mcp.servers.Contains($t.needsConnection)) { $state.mcp.servers[$t.needsConnection].name } else { $LOC.mcp.servers[$t.needsConnection].name }
        $when += "each person first creates the one-time connection to $srv (URL: New-DemoMcpRegistration.ps1 -Action Urls)"
    }
    if ($when.Count) { $lines += "- **When**: $($when -join '; ')" }
    if ($it -and $it.prompt) { $lines += "- **Prompt**: $(Format-Prompt ([string]$it.prompt))" }
    elseif ($it -and $it.prompts) { $lines += "- **Prompts**$(if ($t.sameConversation -ne $false) { ' (same conversation)' }):"; $i = 0; foreach ($p in $it.prompts) { $i++; $lines += "  $i. $(Format-Prompt ([string]$p))" } }
    elseif ($it -and $it.promptSlot) { $lines += "- **Prompt**: $(Get-SlotText ([string]$it.promptSlot))" }
    elseif ($it -and $it.promptSlots) { $lines += '- **Prompts** (same conversation):'; $i = 0; foreach ($s in $it.promptSlots) { $i++; $lines += "  $i. $(Get-SlotText ([string]$s))" } }
    elseif ($t.repeat -and $LOC.tests.items.Contains($t.repeat)) { $lines += "- **Prompt**: as $($t.repeat): $(Format-Prompt ([string]$LOC.tests.items[$t.repeat].prompt))" }
    elseif ($t.uses) { $lines += "- **Prompts**: the baseline $(@($t.uses) -join ', ') (top of this hand-out)" }
    if ($it -and $it.expected) { $lines += "- **Expected**: $(Expand-Prompt ([string]$it.expected))" }
    $lines += (Get-DemoList $t.demos), ''
    return ($lines -join "`n")
}
$ho = @("# Test hand-out · lab $Prefix · $($LOC.language)", '', 'Run the tests in this order; tick each one. Prompts are in the demo language on purpose.', '')
foreach ($k in @($LOC.tests.notes.Keys)) { $ho += "- $($LOC.tests.notes[$k])" }
$ho += '', '## Baseline prompts (every agent)', ''
foreach ($k in @($LOC.tests.baseline.Keys)) {
    $b = $LOC.tests.baseline[$k]
    if ($b.prompt) { $ho += "- **$k**: $(Format-Prompt ([string]$b.prompt)) → $(Expand-Prompt ([string]$b.expected))" }
    else { $ho += "- **$k** (same conversation): $(@($b.prompts | ForEach-Object { Format-Prompt ([string]$_) }) -join ' → ') → $(Expand-Prompt ([string]$b.expected))" }
}
$ho += '', '## Tests', ''
foreach ($t in $pack.tests) { $ho += Get-TestSection $t }

# --- Write the cards ----------------------------------------------------------------------------------------------
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Get-ChildItem -LiteralPath $outDir -Filter '*.md' -ErrorAction SilentlyContinue | Remove-Item -Force
$stamp = "> Lab $(Format-Code $Prefix) · locale $(Format-Code $cfg.locale) · generated $(Get-Date -Format 'yyyy-MM-dd HH:mm') by New-DemoCards.ps1: do not edit, re-run the script."
$index = @()
foreach ($f in @(Get-ChildItem -LiteralPath $tplDir -Filter '*.md' | Sort-Object Name)) {
    $text = Get-Content -LiteralPath $f.FullName -Raw -Encoding utf8
    $text = $text.Replace('<!-- AGENTS:copilotStudio -->', (@(Get-CopilotStudioSections) -join "`n")).Replace('<!-- AGENTS:agentBuilder -->', (@(Get-AgentBuilderSections) -join "`n"))
    $text = Expand-CardText $text
    $title = ([regex]::Match($text, '(?m)^# (.+)$')).Groups[1].Value
    $text = [regex]::Replace($text, '(?m)^(# .+)$', "`$1`n`n$stamp", 1)
    Set-Content -LiteralPath (Join-Path $outDir $f.Name) -Value $text -Encoding utf8
    $index += "- [$title](./$($f.Name))"
}
Set-Content -LiteralPath (Join-Path $outDir '90-test-handout.md') -Value (($ho -join "`n") -replace '(?m)^(# .+)$', "`$1`n`n$stamp") -Encoding utf8
$index += '- [Test hand-out](./90-test-handout.md)'
Set-Content -LiteralPath (Join-Path $outDir '00-index.md') -Value ((@("# Demo cards · lab $Prefix", '', $stamp, '', 'Follow the cards in order; each one says who does it, where, and what the result must be.', '') + $index) -join "`n") -Encoding utf8
$missing = @(Get-ChildItem -LiteralPath $outDir -Filter '*.md' | Select-String -Pattern '<missing [^>]+>' -AllMatches | ForEach-Object { $_.Matches.Value } | Select-Object -Unique)
if ($missing.Count) { Write-DemoLog $Prefix "Cards written with unresolved placeholders: $($missing -join ', ')" 'WARN' }
Write-DemoLog $Prefix "Demo cards written: $outDir ($(@($index).Count) cards incl. the test hand-out)"
